### ISSUE TITLE
Leads to segfault for Qt6 applications

### ISSUE THREAD

**Issue by probonopd** [helloSystem/QKeySequenceOverride#8]
Preloading this leads to Qt5 being loaded in addition to Qt6, which leads to

```
% qtcreator
zsh: segmentation fault  qtcreator
```

We need to find a way to change `QKeySequence::toString()` without using `LD_PRELOAD`. Is the only way to recompile (parts of) Qt?

**Comment by jsm222** [comment]
Not tested at all but perhaps a full implementation like here https://github.com/helloSystem/hello/issues/46#issuecomment-943691568 that not depend on existing binary lib symbol could sort out the Qt5/6 conflict..

**Comment by jsm222** [comment]
perhaps this change is the course https://codereview.qt-project.org/c/qt/qtbase/+/281289/42 I am looking into it..

**Comment by probonopd** [comment]
GammaRay is inserting something into running applications; before it does that, it seems to check for the Qt version, among other things. Not sure, but maybe we can learn something from there.
https://github.com/KDAB/GammaRay/wiki/Troubleshooting

**Comment by jsm222** [comment]
The thing is that qt5 and qt6 shares the symbol we want to override so either if the preloaded so is compiled for qt5 it works with qt5, and the same for qt6 but not at the same time . in other words because the symbol we are overriding is the same in both qt versions we cannot preload two versions.
